### ISSUE TITLE
Does next-type need an intermediate size between 3 and 4? Looks too small on mobile?

### ISSUE THREAD

**Issue by keirog** [Financial-Times/next-type#22]
Grabbed from https://github.com/Financial-Times/next-article/pull/522

**Comment by keirog** [comment]
Hard to capture the feel of it here, but 15px (next-type variant 4) definitely feels too small on my iphone 6:

15px (current next-type 4)
![15](https://cloud.githubusercontent.com/assets/150157/8184540/dae9d1a6-1436-11e5-9afb-b72089badb56.png)

17px
![17](https://cloud.githubusercontent.com/assets/150157/8184543/de9b12ec-1436-11e5-9a7c-1292cada0fb5.png)

20px (current next-type variant 3)
![20](https://cloud.githubusercontent.com/assets/150157/8184545/e1df385c-1436-11e5-96a5-e2245b76d9ea.png)

**Comment by matthew-andrews** [comment]
:+1: to bigger font size!!!

cc @simonwilliamsFT

**Comment by i-like-robots** [comment]
Is the weight of the font also an issue? We should test this on a few different devices.

**Comment by keirog** [comment]
Yeah maybe, it does seem too light. I'll try and organize some devices for a testing session.

**Comment by keirog** [comment]
Just making it bigger for now

**Comment by keirog** [comment]
(See [o-typography](https://github.com/Financial-Times/o-typography) for current sizes)
